CREATE TABLE IF NOT EXISTS `ipcs`.`message_type` (
  `message_type_objid` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  `date_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`message_type_objid`))
ENGINE = InnoDB