CREATE TABLE IF NOT EXISTS `ipcs`.`role` (
  `role_objid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `date_created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`role_objid`),
  UNIQUE INDEX `person_objid_UNIQUE` (`role_objid` ASC),
  UNIQUE INDEX `account_name_UNIQUE` (`name` ASC)
  )
ENGINE = InnoDB