delete from person_role;
delete from person_school;
delete from role_permission;
delete from role;
delete from person;
delete from permission;
delete from school;
delete from school_type;
delete from role;
